export const USERNAME = "userName"
export const PASSWORD = "password"
export const NAME = "fromUser";
export const ORDER_NUMBER = "orderNumber";
export const DOC_NO = "documentNo";
export const PRIORITY = "priority";
export const BRANCH = "branch";
export const DEPARTMENT = "department";
export const SUB_DEPARTMENT = "subDepartment";
export const TO_USER = "country";
export const STATUS = "status";
export const SUBJECT = "subject";
export const FLOW_EMAIL_BODY = "flowEmailBody";
export const OA_FAILURE_TYPE= "oaFailureType";